/*
 * JSP generated by Resin 2.1.10 (built Wed Jun 18 09:16:53 PDT 2003)
 */

import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import ru.juga.dev.matrix.math.matrix.*;
import ru.juga.dev.matrix.webapp.db.*;
import ru.juga.dev.matrix.webapp.filter.*;
import java.sql.*;

public class _index__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html; charset=windows-1251");
    request.setCharacterEncoding("windows-1251");
    tags.PrintMatrix _jsp_tag0 = null;
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
       
Matrix A = null;
if (request.getParameter("inp_mtx")!=null){
A = MatrixPOST.parse(request.getParameter("inp_mtx")); 
DB thread = new DB(request.getParameter("inp_mtx"));
thread.start();
	}

      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      if (A!=null){
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      out.print(( A ));
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      }
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      
if (A!=null) 	{

      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      if (_jsp_tag0 == null) {
        _jsp_tag0 = new tags.PrintMatrix();
        _jsp_tag0.setPageContext(pageContext);
        _jsp_tag0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag0.setCellpadding(5);
      }

      _jsp_tag0.setMatrix( A );
      _jsp_tag0.doStartTag();
      int _jsp_endTagVar3 = _jsp_tag0.doEndTag();
      if (_jsp_endTagVar3 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      out.print(( A.getRang() ));
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      if (A.isKvadrat()){
Q det = A.getDet();

      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      out.print(( det ));
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      if (!det.equals(new Q("0"))){
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      if (_jsp_tag0 == null) {
        _jsp_tag0 = new tags.PrintMatrix();
        _jsp_tag0.setPageContext(pageContext);
        _jsp_tag0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_tag0.setCellpadding(5);
      }

      _jsp_tag0.setMatrix( Matrix.reverse(A) );
      _jsp_tag0.doStartTag();
      int _jsp_endTagVar7 = _jsp_tag0.doEndTag();
      if (_jsp_endTagVar7 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      }}
      pageContext.write(_jsp_string11, 0, _jsp_string11.length);
       
		}else {
 
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      
ResultSet rs = null;
 try {

         Class.forName("com.mysql.jdbc.Driver");

      }
      catch(ClassNotFoundException e) {
         e.printStackTrace();
      }
  Connection con = null;
      try {
         Connection conn = DriverManager.getConnection(
            "jdbc:mysql://localhost/matrix?useUnicode=true&characterEncoding=utf-8",
	 "matrix",
	 "jgNC4T");
         Statement stmt = conn.createStatement();
	rs = stmt.executeQuery("select max(PostID) from PostHistory");

if (rs.next()){

out.println("<table cellspacing='1' width='100%'>");
out.println("<TR>");
out.println("<TD align='center' width='110' bgcolor='#FFFFF1'>\u041f\u0440\u0435\u0434\u044b\u0434\u0443\u0449\u0438\u0435 \u0437\u0430\u043f\u0440\u043e\u0441\u044b:");
out.println("<TD align='left' bgcolor='#FFFFFF'>");

	rs = stmt.executeQuery("select * from postHistory where PostID<="+rs.getString("max(PostID)"));
rs.last();
rs.next();
int k=0;
	while(rs.previous()){
if (k++>=10) break;
			out.println("<TR><TD align='center' width=110 bgcolor='#FFFFF1'>");
			out.println("<TD align='left' bgcolor='#FFFFFF'>");
			out.println(rs.getString("PostBody").replaceAll("\r\n","<br>\r\n"));
			}
 	 }
}//if
      catch(SQLException sqe) {
	out.println(sqe);
	out.println(sqe.getMessage());

      }


      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
       		} 

      pageContext.write(_jsp_string14, 0, _jsp_string14.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_tag0 != null)
        _jsp_tag0.release();
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -2089842225)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_index__jsp.java", "c:\\Program Files\\Java\\resin-ee-2.1.10\\doc\\matrix_dev\\index.jsp");
    _caucho_line_map.add("/matrix_dev/index.jsp", 10, 1);
    _caucho_line_map.add("/plugin/requestHistory.jsp", 2, 1);
    _caucho_line_map.add("/matrix_dev/index.jsp", 3, 32);
    _caucho_line_map.add(5, 33);
    _caucho_line_map.add(10, 36);
    _caucho_line_map.add(26, 46);
    _caucho_line_map.add(27, 48);
    _caucho_line_map.add(28, 50);
    _caucho_line_map.add(38, 52);
    _caucho_line_map.add(41, 56);
    _caucho_line_map.add("/plugin/mtxProperty.jsp", 5, 57);
    _caucho_line_map.add(8, 70);
    _caucho_line_map.add(9, 72);
    _caucho_line_map.add(14, 76);
    _caucho_line_map.add(20, 80);
    _caucho_line_map.add(21, 93);
    _caucho_line_map.add("c:\\Program Files\\Java\\resin-ee-2.1.10\\doc\\matrix_dev\\index.jsp", 42, 95);
    _caucho_line_map.add(45, 99);
    _caucho_line_map.add("/plugin/requestHistory.jsp", 2, 100);
    _caucho_line_map.add(7, 101);
    _caucho_line_map.add("c:\\Program Files\\Java\\resin-ee-2.1.10\\doc\\matrix_dev\\index.jsp", 46, 147);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("plugin/mtxProperty.jsp"), 1099308983093L, 750L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("plugin/requestHistory.jsp"), 1099330978078L, 1296L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("index.jsp"), 1099320385187L, 2003L);
    _caucho_depends.add(depend);
  }

  protected void _caucho_clearDepends()
  {
    _caucho_depends.clear();
  }

  private static byte []_jsp_string9;
  private static byte []_jsp_string10;
  private static byte []_jsp_string11;
  private static byte []_jsp_string13;
  private static byte []_jsp_string14;
  private static byte []_jsp_string0;
  private static byte []_jsp_string12;
  private static byte []_jsp_string7;
  private static byte []_jsp_string3;
  private static byte []_jsp_string4;
  private static byte []_jsp_string8;
  private static byte []_jsp_string1;
  private static byte []_jsp_string2;
  private static byte []_jsp_string5;
  private static byte []_jsp_string6;
  static {
    try {
      _jsp_string9 = "\r\n<TR>\r\n<TD align=\"center\" width=\"110\" bgcolor=\"#FFFFF1\"> \u041e\u043f\u0440\u0435\u0434\u0435\u043b\u0438\u0442\u0435\u043b\u044c \r\n<TD align=\"left\" bgcolor=\"#FFFFFF\"> &nbsp&nbsp ".getBytes("Cp1251");
      _jsp_string10 = "\r\n<TR>\r\n<TD align=\"center\" width=\"110\" bgcolor=\"#FFFFF1\"> \u041e\u0431\u0440\u0430\u0442\u043d\u0430\u044f \u043c\u0430\u0442\u0440\u0438\u0446\u0430\r\n<TD align=\"left\" bgcolor=\"#FFFFFF\">\r\n".getBytes("Cp1251");
      _jsp_string11 = "\r\n\r\n\r\n</table> \r\n ".getBytes("Cp1251");
      _jsp_string13 = "\r\n</table>\r\n \r\n".getBytes("Cp1251");
      _jsp_string14 = "\r\n\r\n<br>\r\n<br>\r\n<br>\r\n\r\n<table cellspacing=\"1\" width=\"100%\">\r\n<TR><Td>\r\n<!--begin of Top100 logo-->\r\n<a href=\"http://top100.rambler.ru/top100/\">\r\n<img src=\"http://top100-images.rambler.ru/top100/w1.gif\" alt=\"Rambler's Top100\" width=88 height=31 border=0></a>\r\n<!--end of Top100 logo -->\r\n<Td align=\"right\">\r\n<address><A HREF=\"mailto:nikolais@mail.ru\">remaL\u00a92004</A></address>\r\n<TR>\r\n</table>\r\n<!--begin of Rambler's Top100 code -->\r\n<a href=\"http://top100.rambler.ru/top100/\">\r\n<img src=\"http://counter.rambler.ru/top100.cnt?642655\" alt=\"\" width=1 height=1 border=0></a>\r\n<!--end of Top100 code-->\r\n</body>\r\n</html>".getBytes("Cp1251");
      _jsp_string0 = "<html>\r\n<body  bgcolor=\"#4C6C8F\" link=\"#FFFFFG\" vlink=\"#FFFFFG\" alink=\"red\">\r\n".getBytes("Cp1251");
      _jsp_string12 = "\r\n\r\n\r\n\r\n\r\n".getBytes("Cp1251");
      _jsp_string7 = "<table cellspacing=\"1\" width=\"100%\">\r\n<TR>\r\n<TD align=\"center\" width=\"110\" bgcolor=\"#FFFFF1\">\u041c\u0430\u0442\u0440\u0438\u0446\u0430 \r\n<TD align=\"left\" bgcolor=\"#FFFFFF\">\r\n".getBytes("Cp1251");
      _jsp_string3 = "\r\n\r\n\r\n".getBytes("Cp1251");
      _jsp_string4 = "\r\n<!-- &nbsp&nbsp&nbsp\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u044d\u043b\u0435\u043c\u0435\u043d\u0442\u044b \u043c\u0430\u0442\u0440\u0438\u0446\u044b, \u0447\u0435\u0440\u0435\u0437 \u043f\u0440\u043e\u0431\u0435\u043b.-->\r\n<table width=\"100%\" border=\"5\" cellspacing=\"0\" cellpadding=\"1\" frame=\"below\">\r\n<tr>\r\n<TD width=\"110\" align=\"center\" bgcolor=\"#FFFFFF\"> <A HREF=\"http://matrix.dev.juga.ru/\"> <img src=\"img/lab2.jpg\" vspace=\"0\" hspace=\"0\"> </A>\r\n<TD width=\"200\" align=\"left\"  bgcolor=\"#FFFFFG\">\r\n<form name=\"sendform\" action=\"index.jsp\" method=\"post\">\r\n<textarea name=\"inp_mtx\" Rows=\"7\" Cols=\"35\">\r\n".getBytes("Cp1251");
      _jsp_string8 = "\r\n<TR>\r\n<TD align=\"center\" width=\"110\" bgcolor=\"#FFFFF1\"> \u0420\u0430\u043d\u0433 \u043c\u0430\u0442\u0440\u0438\u0446\u044b \r\n<TD align=\"left\" bgcolor=\"#FFFFFF\"> &nbsp&nbsp ".getBytes("Cp1251");
      _jsp_string1 = "\r\n\r\n".getBytes("Cp1251");
      _jsp_string2 = "\r\n".getBytes("Cp1251");
      _jsp_string5 = "\r\n</textarea>\r\n<TD  align=\"center\"  bgcolor=\"#FFFFFG\" valign=\"bottom\">\r\n &nbsp&nbsp&nbsp\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u044d\u043b\u0435\u043c\u0435\u043d\u0442\u044b \u043c\u0430\u0442\u0440\u0438\u0446\u044b, \u0447\u0435\u0440\u0435\u0437 \u043f\u0440\u043e\u0431\u0435\u043b.\r\n<br>\r\n<br>\r\n<input type=\"submit\" value=\"\u0412\u044b\u0447\u0438\u0441\u043b\u0438\u0442\u044c\">\r\n\r\n</form>\r\n</table>\r\n".getBytes("Cp1251");
      _jsp_string6 = "\r\n		".getBytes("Cp1251");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
